version: '3.4'

networks:
 backend:

services:
  customerdb:
   container_name: customer-db
   image: mcr.microsoft.com/mssql/server:2022-latest
   environment: 
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Admin123@
   networks:
    - backend
   ports:
    - 8003:1433 
   
  customerwebapi:
    container_name: customer-api
    image: ${DOCKER_REGISTRY-}customerwebapi
    build:
      context: .
      dockerfile: CustomerWebApi/Dockerfile
    networks :
     - backend
    ports:
     - 8002:80 
    environment:
     - DB_HOST=customerdb
     - DB_NAME=customer
     - DB_SA_PASSWORD=Admin123@
